stages:
  - format
  - plan-master
  - apply-master
  - destroy-master
  - publish

variables:
  AWS_ROLE_NAME: gitlab_runner
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  AWS_PROFILE_NAME: cmdlabtf-sandpit


format:
  stage: format
  tags:
    - cmd
  script:
    - make formatCheck

plan-master:
  stage: plan-master
  script:
    - make plan
  tags:
    - cmd

apply-master:
  stage: apply-master
  script:
    - make apply
  tags:
    - cmd

destroy-master:
  stage: destroy-master
  script:
    - make destroy
  tags:
    - cmd

publish:
  stage: publish
  tags:
    - cmd
  script:
    - make publish
  variables:
    GIT_STRATEGY: clone
  only:
    - master
    - tags